encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'encyclopedia'

urlpatterns = [
	path("", views.index, name="index"),
	path('search/', views.search, name='search'),
	path('new_entry/', views.new_entry, name='create_new_entry'),
	path('confirm_new_entry/', views.confirm_new_entry, name='confirm_new_entry'),
	path('edit_entry/<str:entry_title>/', views.edit_entry, name='edit_entry'),
	path('save_changes/<str:entry_title>/', views.save_changes_after_edit, name='save_changes'),
	path('random_page/', views.random_page, name='random_page'),
	path('<str:entry_title>/', views.entry_page, name='entry_page')
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('encyclopedia.urls'))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render

from . import util


def index(request):
	return render(request, "encyclopedia/index.html", {
		"entries_names": util.list_entries()
	})


def entry_page(request, entry_title: str):
	from collections import namedtuple
	import markdown2

	entry_content = util.get_entry(entry_title)

	if entry_content:
		entry_content = markdown2.markdown(entry_content)
		Entry = namedtuple('Entry', 'title content')
		
		return render(request, 'encyclopedia/entry_page.html', {
			'entry': Entry(entry_title, entry_content),
		})
	else:
		return render(request, 'encyclopedia/error_page.html', { 
			'title': f'{entry_title} not found',
			'message': 'The page you\'re looking for, may not exist 🤔'
		})


def random_page(request):
	from random import randint
	
	entries_titles: list(str) = util.list_entries()

	random_index = randint(0, len(entries_titles)-1)
	random_title = entries_titles[random_index]

	return entry_page(request, random_title)


def new_entry(request):
	return render(request, 'encyclopedia/create_new_entry.html')


def confirm_new_entry(request):
	from django.http import HttpResponse

	title: str = request.POST['title']
	content = request.POST['content']

	if title != '' and content != '':
		entries_titles: list(str) = util.list_entries()

		# see if this entry already exists
		for entry_title in entries_titles:
			if title.upper() == entry_title.upper():
				return render(request, 'encyclopedia/error_page.html', {
					'title': f'{title} already exists',
					'message': 'This entry already exists 😐 try to create another one'
				})

		# if it doesn't exist
		util.save_entry(title, content)

		return entry_page(request, title)
	else:
		return render(request, 'encyclopedia/error_page.html', {
			'title': 'Fill all the fields',
			'message': 'Don\'t leave any blank fields 😉 right?'
		})


def edit_entry(request, entry_title: str):
	from collections import namedtuple

	entry_content = util.get_entry(entry_title)

	Entry = namedtuple('Entry', 'title content')

	return render(request, 'encyclopedia/edit_entry.html', {
		'entry': Entry(entry_title, entry_content)
	})


def save_changes_after_edit(request, entry_title: str):
	entry_content = request.POST['content']

	util.save_entry(entry_title, entry_content)

	return entry_page(request, entry_title)


def search(request):
	import re

	entries_titles: list(str) = util.list_entries()
	searched_value: str = request.GET['search_value']

	entries_that_match: list(str) = []

	for entry_title in entries_titles:
		if searched_value.upper() == entry_title.upper():
			return entry_page(request, searched_value)
		elif re.search(searched_value.upper(), entry_title.upper()):
			entries_that_match.append(entry_title)

	if entries_that_match == []:
		return render(request, 'encyclopedia/error_page.html', { 
			'title': f'{entry_title} not found',
			'message': 'Sorry, no results for this entry 😅'
		})

	return render(request, 'encyclopedia/search_results.html', { 
		'entries_titles': entries_that_match
	})

encyclopedia/templates/encyclopedia/create_new_entry.html
{% extends './layout.html' %}

{% block body %}
	<form action="{% url 'encyclopedia:confirm_new_entry' %}" method="POST">
		{% csrf_token %}
		
		<label for="title">Title</label>
		<input type="text" name="title" placeholder="Enter the title of the entry">
		<br>
		<label for="content">Content</label>
		<br>
		<textarea 
			name="content" 
			cols="20" 
			rows="8" 
			style="height: 60vh" 
			placeholder="Enter the markdown content of this entry"
		></textarea>
		<br>
		<button>Submit data</button>
	</form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit_entry.html
{% extends './layout.html' %}

{% block title %}
	{{ entry.title }}
{% endblock %}

{% block body %}
	<form action="{% url 'encyclopedia:save_changes' entry.title %}" method="POST">
		{% csrf_token %}

		<textarea style="height: 60vh" name="content" cols="20" rows="8">{{ entry.content }}</textarea>
		<br>
		<button>Save changes</button>
	</form>
{% endblock %}

encyclopedia/templates/encyclopedia/entry_page.html
{% extends './layout.html' %}

{% block title %}
	{{ entry.title }}
{% endblock %}

{% block body %}
	{{ entry.content|safe }}

	<a href="{% url 'encyclopedia:edit_entry' entry.title %}">Edit entry</a>
{% endblock %}

encyclopedia/templates/encyclopedia/error_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static 'encyclopedia/error_page_styles.css' %}">
	<title>{{ title }}</title>
</head>
<body>
	<div class="container">
		<div class="heading">
			<h1>Something went wrong...</h1>
			<h2>{{ message }}</h2>
			<div class="buttonHome">
				<a href="{% url 'encyclopedia:index' %}">Go to home page</a>
			</div>
		</div>
	</div>
</body>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries_names %}
            <li><a href="{{entry}}/">
                {{ entry }}
            </a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="search_value" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create_new_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search_results.html
{% extends './layout.html' %}

{% block body %}
	<h1>search results</h1>

	<ul>
		{% for entry_title in entries_titles %}
			<li>
				<a href="{% url 'encyclopedia:entry_page' entry_title %}">{{ entry_title }}</a>
			</li>
		{% endfor %}
	</ul>
{% endblock %}